version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      runtime:
        patterns:
          - "perplexityai"
      dev:
        patterns:
          - "prek"
          - "pytest-error-for-skips"
          - "pytest-homeassistant-custom-component"
          - "ruff"
          - "ty"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "weekly"
