name: Prek auto-update

on:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  auto-update:
    name: Prek auto-update
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.14
          cache: pip

      - name: Install uv
        run: pip install uv

      - name: Install pre-commit
        run: uv pip install --system prek

      - name: Run pre-commit autoupdate
        run: prek auto-update

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update/prek-auto-update
          title: Auto-update prek hooks
          commit-message: Auto-update prek hooks
          body: |
            Update versions of tools in prek
            configs to latest version
          labels: dependencies
